version: 2
updates:
  # Esempio per npm (Node.js)
    directory: "/"
    schedule:
      interval: "weekly"
    
  # Esempio per GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"